import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import NextAuthSessionProvider from "@/providers/sessionProviders";
import Providers from "@/providers/Providers";
import Nav from "@/app/_components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mayday",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <NextAuthSessionProvider>
            <main>{children}</main>
            <Toaster />
          </NextAuthSessionProvider>
        </body>
      </Providers>
    </html>
  );
}
