import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import NextAuthSessionProvider from "@/providers/sessionProviders";
import NavItems from "@/app/_components/nav/navItems";
import UserNav from "@/app/_components/nav/usernav";
import getCurrentUser from "@/app/_actions/getCurrentUser";
import Providers from "@/providers/Providers";
import Link from "next/link";
import { cn } from "@/lib/utils";
import { JsonArray } from "@prisma/client/runtime/library";
import NavAdminItems from "./_components/nav/nav-admin-item";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mayday",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getCurrentUser();

  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <NextAuthSessionProvider>
            <main>
              {session !== null && (
                <>
                  <div className="border-b">
                    <div className="flex h-16 items-center px-4">
                      <h1 className="font-bold text-xl">Mayday</h1>
                      <NavItems className="mx-6" />
                      <div className="ml-auto flex items-center space-x-4">
                        {((session &&
                          session.profile.permissions &&
                          Array.from(
                            session.profile.permissions as JsonArray
                          ).includes("admin.*")) ||
                          Array.from(
                            session.profile.permissions as JsonArray
                          ).includes("admin.view")) && <NavAdminItems />}
                        <UserNav />
                      </div>
                    </div>
                  </div>
                  <div className="container mx-auto">{children}</div>
                </>
              )}
              {session === null && (
                <div className="h-screen flex justify-center items-center">
                  {children}
                </div>
              )}
            </main>
            <Toaster />
          </NextAuthSessionProvider>
        </body>
      </Providers>
    </html>
  );
}
